Repository dotnet/dotnet-monitor, pull requests merged in 2021-04, with the labels that each got.

#149 Mark dotnet-monitor as shipping
  src/Directory.Build.props
  src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
  src/Tools/Directory.Build.props
Labels: auto-merge

#151 [release/5.0] Mark dotnet-monitor as shipping
  src/Directory.Build.props
  src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
  src/Tools/Directory.Build.props
Labels: auto-merge

#197 Additional API docs for /logs
  documentation/README.md
  documentation/api/definitions.md
  documentation/api/dump.md
  documentation/api/gcdump.md
  documentation/api/logs.md
  documentation/api/processes-env.md
  documentation/api/processes-get.md
  documentation/api/trace-custom.md
  documentation/api/trace-get.md
Labels: documentation

#211 Documentation for egress providers
  documentation/README.md
  documentation/configuration.md
  documentation/egress.md
  documentation/troubleshooting.md
  src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProviderOptions.cs
Labels: documentation

#214 Add egressProvider parameter to API docs.
  documentation/api/dump.md
  documentation/api/gcdump.md
  documentation/api/logs.md
  documentation/api/metrics.md
  documentation/api/trace-custom.md
  documentation/api/trace-get.md
Labels: documentation

#217 Mirror scrips from diagnostic for fixes
  eng/release/Scripts/AcquireBuild.ps1
Labels: auto-merge

#172 Add process environment tests and dump tests
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/IDiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Models/DumpType.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LoggingRunnerAdapter.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/AuthenticationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/DiagnosticPortHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/DisposableBox.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/DumpTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiStatusCodeException.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ContentTypes.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ResponseStreamHolder.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ValidationProblemDetailsException.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/MetricsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Microsoft.Diagnostics.Monitoring.UnitTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/ProcessTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/AppRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/MonitorRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/TestConditions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/TestTimeouts.cs
Labels: auto-merge

#241 Write ndjson logs in same format at JsonConsoleFormatter and event-stream logs in format as SimpleConsoleFormatter
  src/Microsoft.Diagnostics.Monitoring.RestServer/ScopeState.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs
Labels: enhancement
