Repository dotnet/dotnet-monitor, pull requests merged in 2021-12, with the labels that each got.

#1197 Update current releases documentation with 6.0.1 release
  documentation/releases.md
Labels: documentation

#1199 Add LoadProfiler action
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/LoadProfilerAction.cs
  src/Tools/dotnet-monitor/CollectionRules/KnownCollectionRuleActions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/LoadProfilerOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/RequiredGuidAttribute.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: enhancement, servicing-major

#1218 Refactor configuration setup and command handling into separate files
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: auto-merge
