Repository dotnet/dotnet-monitor, pull requests merged in 2022-01, with the labels that each got.

#1300 Fix logging message for exit code in AppRunner
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs
Labels: servicing-patch

#1298 Add backport action.
  .github/workflows/backport.yml
  eng/actions/backport/action.yml
  eng/actions/backport/index.js
Labels: servicing-patch

#1352 Add net7.0 TFM to dotnet-monitor.
  eng/Versions.props
  global.json
  src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj
  src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests.csproj
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: auto-merge

#1372 Add configuration ordering tests.
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HostBuilderExtensions.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/HostBuilderSettings.cs
Labels: testing, servicing-patch

#1371 Simplified Diagnostic Port Configuration
  documentation/schema.json
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
  src/Tools/dotnet-monitor/DiagnosticPortPostConfigureOptions.cs
Labels: servicing-minor

#1382 Push command line url parameters to lowest precedence.
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
Labels: servicing-patch, servicing-minor
