Repository dotnet/dotnet-monitor, pull requests merged in 2022-07, with the labels that each got.

#2074 Fix version file names that are published to blob storage
  eng/Publishing.props
  src/Directory.Build.targets
Labels: servicing-patch, servicing-minor, servicing-major

#2119 Collect Live Metrics Action
  documentation/collectionrules/collectionrules.md
  documentation/configuration.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/MetricsUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CounterPayload.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LiveMetricsTestUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
  src/Tools/dotnet-monitor/CollectionRules/KnownCollectionRuleActions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptionsDefaults.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: servicing-minor

#2165 Replace redundant LiveJwtBearerHandler with standard JwtBearerHandler
  src/Tools/dotnet-monitor/Auth/LiveJwtBearerHandler.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: servicing-patch, servicing-minor

#2149 Fix duplicated values for matric group
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/MetricsExportTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/PrometheusDataModelTests.cs
Labels: servicing-patch, servicing-minor

#2164 Delete endpoint on startup
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-patch, servicing-minor
