Repository dotnet/dotnet-monitor, pull requests merged in 2022-10, with the labels that each got.

#2607 Add missing documentation, links, and 6.3+ qualifier
  documentation/README.md
  documentation/api/README.md
  documentation/api/collectionrules-get.md
  documentation/api/collectionrules-list.md
  documentation/api/collectionrules.md
  documentation/api/definitions.md
  documentation/api/operations-list.md
  documentation/configuration.md
Labels: documentation

#2554 Update docs with experimental configuration
  documentation/api/README.md
  documentation/api/definitions.md
  documentation/api/stacks.md
  documentation/configuration.md
  documentation/experimental.md
Labels: documentation

#2601 Run apps with test frameworks by using customized runtimeconfig.json
  src/Directory.Build.targets
  src/Tests/Directory.Build.props
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetFrameworkReference.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
Labels: testing

#2640 Scripts to launch VS and VS Code using local SDK
  generate-dev-sln.ps1
  startvs.cmd
  startvscode.cmd
  startvscode.sh
Labels: servicing-minor, servicing-major

#2647 Use latest docker containers
  eng/build.yml
Labels: servicing-minor, servicing-major

#2663 Update ASP.NET libraries and test runtime versions
  eng/Versions.props
Labels: servicing-major, dependencies

#2672 Fixing broken links and typos
  documentation/api/collectionrules-get.md
  documentation/api/collectionrules-list.md
  documentation/api/definitions.md
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/LoggingExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs
Labels: servicing-major

#2637 Split process stop from disposal and use disposal helpers
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/EnumerableExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTestsHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionBase.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
Labels: testing, servicing-major

#2643 Refactor logs capture and faster logs functional testing
  src/Microsoft.Diagnostics.Monitoring.WebApi/ArtifactOperationExetensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IArtifactOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ILogsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/LogsUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LogsTestUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.Artifacts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/EventSourceArtifactOperation.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Logs/LogsOperation.cs
  src/Tools/dotnet-monitor/Logs/LogsOperationFactory.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: testing, servicing-minor, servicing-major

#2694 Update ASP.NET libraries and test runtime versions
  eng/Versions.props
Labels: dependencies

#2700 Remove StaticWebAssets disablement workaround
  src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-major

#2718 Remove .NET Core 3.1 build and testing
  eng/Versions.props
  eng/build.yml
Labels: testing, servicing-major

#2695 Merge execute action app into unit test app
  dotnet-monitor.sln
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ActionTestsConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTestHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs
Labels: testing, servicing-minor, servicing-major

#2730 [release/6.x] Refactor logs capture and faster logs functional testing
  src/Microsoft.Diagnostics.Monitoring.WebApi/ArtifactOperationExetensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IArtifactOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ILogsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/LogsUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LogsTestUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.Artifacts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/EventSourceArtifactOperation.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Logs/LogsOperation.cs
  src/Tools/dotnet-monitor/Logs/LogsOperationFactory.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: backport

#2732 [release/7.x] Merge execute action app into unit test app
  dotnet-monitor.sln
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ActionTestsConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTestHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs
Labels: backport

#2731 [release/6.x] Run apps with test frameworks by using customized runtimeconfig.json
  src/Directory.Build.targets
  src/Tests/Directory.Build.props
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetFrameworkReference.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs
Labels: backport

#2733 [release/6.x] Merge execute action app into unit test app
  dotnet-monitor.sln
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ActionTestsConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTestHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs
Labels: backport

#2740 Remove installation of .NET Core 3.1 frameworks
  global.json
Labels: testing, servicing-major

#2755 Skip test that fails due to Azurite update
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/AzureBlob/AzureBlobEgressProviderTests.cs
Labels: servicing-minor, servicing-major

#2796 Fix Roslyn analyzers commit hash
  eng/Version.Details.xml
Labels: dependencies

#2806 Handle exceptions when collecting additional info for discovered processes
  src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
Labels: servicing-patch, servicing-major, update-release-notes

#2813 [release/7.x] Handle exceptions when collecting additional info for discovered processes
  src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
Labels: backport

#2815 Handle all non-cancellation exceptions when creating IProcessInfo
  src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
Labels: servicing-minor, servicing-major
