Repository dotnet/dotnet-monitor, pull requests merged in 2022-08, with the labels that each got.

#2136 Operations Api shows RuntimeId, ProcessId, and ProcessName
  documentation/api/operations-get.md
  documentation/api/operations-list.md
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EgressOperationStatus.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperation.cs
Labels: servicing-minor

#2250 Fix executable permissions on dotnet.sh script
  dotnet.sh
Labels: servicing-patch, servicing-minor

#2264 Update to newer Windows build machines
  dotnet-monitor-codeql.yml
  dotnet-monitor.yml
  eng/PrepareRelease.yml
  eng/build.yml
  eng/release.yml
Labels: servicing-patch, servicing-minor

#2232 Check Read Permissions For JSON Configuration Sources
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-minor

#2285 Update runtimes to latest
  eng/Versions.props
Labels: servicing-patch, dependencies

#2284 Update runtimes and SDK to latest
  eng/Versions.props
  global.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: dependencies

#2345 Update to newer Windows build images
  dotnet-monitor-codeql.yml
  dotnet-monitor.yml
  eng/PrepareRelease.yml
  eng/build.yml
Labels: servicing-patch

#2380 Breaking changes doc
  documentation/README.md
  documentation/compatibility/7.0/README.md
  documentation/compatibility/README.md
Labels: documentation
