Repository dotnet/dotnet-monitor, pull requests merged in 2022-03, with the labels that each got.

#1464 Push a Message to a Queue When Writing to Azure Egress
  documentation/configuration.md
  documentation/schema.json
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedConfigurations/EgressRedacted.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressRedacted.json
  src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
  src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-minor

#1602 Add experience survey link
  documentation/releaseNotes/releaseNotes.md
  src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/ExperienceSurvey.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-minor, servicing-major

#1647 Update release process with storage account publishing steps
  documentation/release-process.md
Labels: documentation
