Repository dotnet/dotnet-monitor, pull requests merged in 2022-06, with the labels that each got.

#1853 Unhandled exception detection
  src/MonitorProfiler/CMakeLists.txt
  src/MonitorProfiler/Logging/Logger.h
  src/MonitorProfiler/MainProfiler/ExceptionTracker.cpp
  src/MonitorProfiler/MainProfiler/ExceptionTracker.h
  src/MonitorProfiler/MainProfiler/MainProfiler.cpp
  src/MonitorProfiler/MainProfiler/MainProfiler.h
  src/MonitorProfiler/MainProfiler/ThreadData.cpp
  src/MonitorProfiler/MainProfiler/ThreadData.h
  src/MonitorProfiler/MainProfiler/ThreadDataManager.cpp
  src/MonitorProfiler/MainProfiler/ThreadDataManager.h
Labels: servicing-major

#1829 Querying For Collection Rule State
  documentation/api/collectionrules-all.md
  documentation/api/collectionrules-individual.md
  documentation/api/definitions.md
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleFinishedStates.cs
  src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleState.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/CollectionRulePipelineState.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ICollectionRuleService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CollectionRuleDescription.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CollectionRuleDetailedDescription.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTestsHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/ActionsServiceCollectionExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-minor

#2055 Update Newtonsoft.Json version
  eng/Versions.props
  src/Tests/Directory.Build.props
Labels: servicing-patch, servicing-minor

#2061 Update Newtonsoft.Json version
  eng/Versions.props
  src/Tests/Directory.Build.props
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-patch
