Repository dotnet/dotnet-monitor, pull requests merged in 2022-05, with the labels that each got.

#1812 Add configuration section for Egress Extensibility
  src/Microsoft.Diagnostics.Monitoring.Options/ExtensionEgressProviderOptions.cs
  src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
  src/Tools/dotnet-monitor/Egress/Configuration/EgressPropertiesProvider.cs
  src/Tools/dotnet-monitor/Egress/Configuration/EgressProviderConfigurationChangeTokenSource.cs
  src/Tools/dotnet-monitor/Egress/Configuration/EgressProviderConfigurationProvider.cs
  src/Tools/dotnet-monitor/Egress/Configuration/EgressProviderConfigureNamedOptions.cs
  src/Tools/dotnet-monitor/Egress/Configuration/IEgressPropertiesProvider.cs
  src/Tools/dotnet-monitor/Egress/Configuration/IEgressProviderConfigurationProvider.cs
  src/Tools/dotnet-monitor/Egress/Configuration/IOptionsTypeToProviderTypesMapper.cs
  src/Tools/dotnet-monitor/Egress/Configuration/OptionsTypeToProviderTypesMapper.cs
  src/Tools/dotnet-monitor/Egress/EgressProvider.cs
  src/Tools/dotnet-monitor/Egress/EgressProviderInternal.cs
  src/Tools/dotnet-monitor/Egress/EgressService.cs
  src/Tools/dotnet-monitor/Egress/Extension/ExtensionEgressPayload.cs
  src/Tools/dotnet-monitor/Egress/Extension/ExtensionEgressProvider.cs
  src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressProvider.cs
  src/Tools/dotnet-monitor/Egress/IEgressProvider.cs
  src/Tools/dotnet-monitor/Egress/IEgressProviderInternal.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: servicing-minor

#1830 Add warning when collection rules are configured but not running in Listen mode
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-patch, servicing-minor

#1838 Do not warn about unconfigured auth when --no-auth is used
  src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfigurationObserver.cs
Labels: servicing-patch, servicing-minor

#1857 [release/6.1] Remove prerelease blob group
  documentation/release-process.md
  eng/Versions.props
  src/Directory.Build.targets
Labels: servicing-minor

#1858 Fix shipping metadata for blob files
  eng/Publishing.props
Labels: servicing-patch, servicing-minor

#1877 Update OSS Versions
  NuGet.config
  eng/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AsyncWaitScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/EnvironmentVariablesScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs
  src/Tools/dotnet-monitor/Program.cs
Labels: servicing-patch, servicing-minor

#1884 Add support for Managed Identity authentication for egress.
  documentation/configuration.md
  documentation/schema.json
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.Validate.cs
  src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedConfigurations/EgressRedacted.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressRedacted.json
  src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
  src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-major

#1870 Enable using runtime id for profiler communication channel
  src/Microsoft.Diagnostics.Monitoring.WebApi/EndpointInfo/IEndpointInfoSource.cs
  src/MonitorProfiler/CMakeLists.txt
  src/MonitorProfiler/Communication/IpcCommServer.cpp
  src/MonitorProfiler/Environment/EnvironmentHelper.cpp
  src/MonitorProfiler/Environment/EnvironmentHelper.h
  src/MonitorProfiler/Logging/DebugLogger.cpp
  src/MonitorProfiler/Logging/NullLogger.cpp
  src/MonitorProfiler/Logging/NullLogger.h
  src/MonitorProfiler/MainProfiler/MainProfiler.cpp
  src/MonitorProfiler/MainProfiler/MainProfiler.h
  src/MonitorProfiler/Utilities/StringUtilities.h
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/ActionsServiceCollectionExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/PassThroughAction.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs
  src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/BaseRecordOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectDumpOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectGCDumpOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptions.Validate.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.Validate.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/ExecuteOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/GetEnvironmentVariableOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/LoadProfilerOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/SetEnvironmentVariableOptions.cs
  src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: servicing-major
