Repository dotnet/dotnet-monitor, pull requests merged in 2022-09, with the labels that each got.

#2427 Enable building net7.0 in Visual Studio
  eng/Versions.props
Labels: dependencies

#2481 Clear server URLs after setting endpoints on KestrelServerOptions
  src/Tools/dotnet-monitor/AddressListenResults.cs
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Startup.cs
Labels: servicing-minor

#2488 Update SDK to 7.0 RC 1 and runtimes to latest
  eng/Versions.props
  global.json
  src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/TemplateOptions.cs
  src/Tools/dotnet-monitor/RootOptions.cs
Labels: dependencies

#2531 Get CorsConfiguration through options service
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Startup.cs
Labels: servicing-minor

#2541 Use host architecture instead of x64 for runtimes
  global.json
Labels: dependencies

#2542 Use wildcard instead of specific version for TraceEvent exclusions
  src/Directory.Build.targets
Labels: servicing-patch, servicing-minor

#2550 Unwrap ChainedConfigurationProvider to get real provider
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DefaultProcess.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DiagnosticPort.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/URLs.json
  src/Tools/dotnet-monitor/ConfigurationExtensions.cs
  src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
  src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
Labels: servicing-minor

#2551 [release/6.x] Move metrics services configuration out of Startup class
  src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/MetricsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs
  src/Tools/dotnet-monitor/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Startup.cs
Labels: servicing-patch

#2560 [manual] Bump actions/github-script from 3 to 6.3.0
  .github/workflows/backport.yml
  .github/workflows/buildkicker.yml
  eng/actions/buildkicker/action.yml
  eng/actions/buildkicker/buildkicker.js
Labels: dependencies

#2535 Avoid Kestrel address override warning
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/KestrelTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/ConfigurationExtensions.cs
  src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/HostBuilder/ServerUrlsBlockingConfigurationManager.cs
  src/Tools/dotnet-monitor/HostBuilder/ServerUrlsBlockingConfigurationProvider.cs
  src/Tools/dotnet-monitor/HostBuilder/ServerUrlsBlockingConfigurationSource.cs
Labels: servicing-minor

#2571 Allow processinfo to be null when parsing runtime version
  src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs
Labels: servicing-major

#2594 Tie xunit.assert version to xunit version from Arcade
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
Labels: servicing-patch, servicing-major
