Repository dotnet/dotnet-monitor, pull requests merged in 2022-11, with the labels that each got.

#2814 [release/6.x] Handle exceptions when collecting additional info for discovered processes
  src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
Labels: backport

#2835 Support non-EventSource-based piplines as artifact operations
  src/Tools/dotnet-monitor/Logs/LogsOperation.cs
  src/Tools/dotnet-monitor/PipelineArtifactOperation.cs
Labels: servicing-minor, servicing-major

#2016 Add support of egress provider to deliver data to a S3 storage
  documentation/configuration.md
  documentation/schema.json
  eng/Versions.props
  eng/dependabot/Versions.props
  src/Microsoft.Diagnostics.Monitoring.Options/EgressOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.Options/S3StorageEgressProviderOptions.Validate.cs
  src/Microsoft.Diagnostics.Monitoring.Options/S3StorageEgressProviderOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/S3/InMemoryS3.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/S3/MultiPartUploadStreamTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/S3/S3StorageEgressProviderTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/S3StorageEgressProviderOptions.UnitTest.cs
  src/Tools/dotnet-monitor/Egress/EgressProviderTypes.cs
  src/Tools/dotnet-monitor/Egress/S3/IS3Storage.cs
  src/Tools/dotnet-monitor/Egress/S3/MultiPartUploadStream.cs
  src/Tools/dotnet-monitor/Egress/S3/S3Storage.cs
  src/Tools/dotnet-monitor/Egress/S3/S3StorageEgressProvider.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: update-release-notes

#2836 Collect dumps via artifact operation
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IDumpOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/DumpUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Dumps/DumpOperation.cs
  src/Tools/dotnet-monitor/Dumps/DumpOperationFactory.cs
Labels: servicing-minor, servicing-major

#2845 Collect metrics via artifact operation
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IMetricsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/MetricsUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/TestHostHelper.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
Labels: servicing-minor, servicing-major

#2863 Update breaking changes with details
  documentation/compatibility/7.0/README.md
Labels: documentation

#2883 [release/7.x] Collect dumps via artifact operation
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IDumpOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/DumpUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Dumps/DumpOperation.cs
  src/Tools/dotnet-monitor/Dumps/DumpOperationFactory.cs
Labels: backport

#2795 Add support for speedscope format
  documentation/api/definitions.md
  documentation/openapi.json
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypeUtilities.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypes.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/SpeedScopeStackResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerChannel.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs
  src/MonitorProfiler/CMakeLists.txt
  src/MonitorProfiler/MainProfiler/MainProfiler.cpp
  src/MonitorProfiler/Utilities/ThreadUtilities.cpp
  src/MonitorProfiler/Utilities/ThreadUtilities.h
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectStacksAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs
Labels: experimental-feature, update-release-notes

#2858 Remove synchronous IO for metrics
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/StreamingCounterLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs
Labels: servicing-minor, servicing-major

#2945 Update ASP.NET authentication packages to 7.0.0
  eng/Versions.props
Labels: servicing-major, dependencies

#2944 [release/6.x] Bifurcate ASP.NET authentication package versions
  eng/Versions.props
Labels: dependencies
