Repository dotnet/dotnet-monitor, pull requests merged in 2022-12, with the labels that each got.

#2959 Align ASP.NET authentication package versions with ASP.NET framework versions
  eng/Versions.props
Labels: dependencies

#2971 [release/6.x] Align ASP.NET authentication package versions with ASP.NET framework versions
  eng/Versions.props
Labels: backport

#2941 Add support for thread names stack artifacts.
  documentation/api/definitions.md
  documentation/api/stacks.md
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackData.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackEvents.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/JsonStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs
  src/MonitorProfiler/CMakeLists.txt
  src/MonitorProfiler/EventProvider/ProfilerEvent.h
  src/MonitorProfiler/MainProfiler/MainProfiler.cpp
  src/MonitorProfiler/MainProfiler/MainProfiler.h
  src/MonitorProfiler/Stacks/Stack.h
  src/MonitorProfiler/Stacks/StackSampler.cpp
  src/MonitorProfiler/Stacks/StackSampler.h
  src/MonitorProfiler/Stacks/StacksEventProvider.cpp
  src/MonitorProfiler/Stacks/StacksEventProvider.h
  src/MonitorProfiler/Utilities/ThreadNameCache.cpp
  src/MonitorProfiler/Utilities/ThreadNameCache.h
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksScenario.cs
Labels: update-release-notes

#2919 Add Tags for API Requests
  documentation/api/definitions.md
  documentation/api/dump.md
  documentation/api/gcdump.md
  documentation/api/livemetrics-custom.md
  documentation/api/livemetrics-get.md
  documentation/api/logs-custom.md
  documentation/api/logs-get.md
  documentation/api/operations-get.md
  documentation/api/operations-list.md
  documentation/api/stacks.md
  documentation/api/trace-custom.md
  documentation/api/trace-get.md
  documentation/openapi.json
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EgressOperationStatus.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/HttpResponseEgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/Utilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OperationsTests.cs
Labels: update-release-notes

#2939 Add Metadata Support For Metrics
  documentation/api/livemetrics-custom.md
  documentation/configuration.md
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/PrometheusDataModelTests.cs
Labels: update-release-notes

#3044 Publish .NET 8 test results
  eng/build.yml
Labels: auto-merge

#3059 [release/7.x] Pull requests only run .NET 7 tests
  dotnet-monitor.yml
  src/Directory.Build.props
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ProfilerInitializationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs
Labels: backport

#3060 [release/6.x] Pull requests only run .NET 6 tests
  dotnet-monitor.yml
  src/Directory.Build.props
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs
Labels: backport

#3105 Split build and test yaml into separate templates
  dotnet-monitor.yml
  eng/build-test.yml
  eng/build.yml
Labels: servicing-patch, servicing-minor, servicing-major

#3108 [release/7.x] Split build and test yaml into separate templates
  dotnet-monitor.yml
  eng/build-test.yml
  eng/build.yml
Labels: backport

#3102 [release/7.x] Update runtime installation for 7.0
  global.json
Labels: dependencies

#3123 [release/6.x] Split build and test yaml into separate templates
  dotnet-monitor.yml
  eng/build-test.yml
  eng/build.yml
Labels: backport

#3133 [release/6.x] Reorganize pipelines and update CodeQL
  .config/tsaoptions.json
  dotnet-monitor-codeql.yml
  dotnet-monitor.yml
  eng/pipelines/dotnet-monitor-codeql.yml
  eng/pipelines/jobs/build-codeql.yml
  eng/pipelines/jobs/build-test.yml
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/platform-matrix.yml
  eng/pipelines/stages/preparerelease.yml
Labels: backport
