Repository dotnet/dotnet-monitor, pull requests merged in 2023-10, with the labels that each got.

#5456 Remove version file generation and blob publishing
  eng/Publishing.props
  eng/pipelines/jobs/pack-sign-publish.yml
  src/Directory.Build.targets
Labels: servicing-patch, servicing-minor

#5449 Remove coherency attributes from frameworks
  eng/Version.Details.xml
Labels: servicing-patch, servicing-minor, dependencies

#5480 Update xcopy msbuild
  global.json
Labels: dependencies

#5501 Remove net6.0 TFM build and packaging
  documentation/openapi.json
  documentation/schema.json
  eng/Common.props
  eng/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
  src/archives/AzureBlobStorage/ProjectsToPublish.props
  src/archives/S3Storage/ProjectsToPublish.props
  startvs.cmd
Labels: update-release-notes

#5509 Merge internal commits for release/8.x
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies

#5522 Update SDK to 8.0 RC 2
  global.json
Labels: dependencies

#5523 Revert "Update SDK to 8.0 RC 2 (#5522)"
  global.json
Labels: dependencies

#5527 Return HTTP 400 for disabled features
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ControllerExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tools/dotnet-monitor/Experimental/ExperimentalStartupLogger.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: update-release-notes

#5532 Change storage account staging root to build version
  dotnet-monitor.yml
  eng/pipelines/dotnet-monitor-release.yml
  eng/pipelines/stages/preparerelease.yml
  eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs
  eng/release/DiagnosticsReleaseTool/Config.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs
  eng/release/Scripts/PublishToBlobAccounts.ps1
Labels: servicing-patch, servicing-minor, servicing-major

#5541 [release/7.x] Change storage account staging root to build version
  dotnet-monitor.yml
  eng/pipelines/dotnet-monitor-release.yml
  eng/pipelines/stages/preparerelease.yml
  eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs
  eng/release/DiagnosticsReleaseTool/Config.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs
  eng/release/Scripts/PublishToBlobAccounts.ps1
Labels: servicing-patch, servicing-minor

#5570 Use implicit xcopy-msbuild version
  global.json
Labels: dependencies

#5594 Use final stable version
  eng/Versions.props
Labels: dependencies

#5622 Add missing script
  eng/release/Scripts/SetTaskVariable.ps1
Labels: needs-review
