Repository dotnet/dotnet-monitor, pull requests merged in 2023-07, with the labels that each got.

#4828 Add versions for Helix
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: dependencies

#4830 Use TEST_DOTNET_ROOT in testing to override dotnet executable location
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs
Labels: testing

#4845 Use environment variable to indicate that Azurite must initialize
  eng/pipelines/jobs/test-binaries.yml
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs
Labels: testing

#4846 Remove restriction of running tests in cross build
  eng/build.ps1
  eng/build.sh
Labels: testing

#4883 Fix Collection Rule Trigger Type Console Spew
  src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs
Labels: update-release-notes

#4826 Enable operation tracking for trigger actions
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/RequestThrottling/RequestLimitTracker.cs
  src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/CollectGCDumpActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/CollectLiveMetricsActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/CollectTraceActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/CollectionRuleActions.UnitTests/LoadProfilerActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectTraceTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/CollectionRules/Actions/CallbackAction.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/CollectionRules/Actions/PassThroughAction.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/EndpointInfoSourceCallback.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/TestHostHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTestsHelper.cs
  src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs
  src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectGCDumpAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectStacksAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionBase.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionFactoryProxy.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/ExecuteAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/GetEnvironmentVariableAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleActionFactory.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleActionFactoryProxy.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/LoadProfilerAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/SetEnvironmentVariableAction.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs
  src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContext.cs
Labels: servicing-major, update-release-notes

#4901 Add documentation for exceptions history feature
  cspell.json
  documentation/README.md
  documentation/api/README.md
  documentation/api/definitions.md
  documentation/api/exceptions.md
  documentation/configuration/in-process-features-configuration.md
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
Labels: update-release-notes

#4847 Add Helix project and supporting targets
  eng/Helix.CrossTarget.targets
  eng/Helix.SingleTarget.targets
  eng/Helix.props
  eng/Helix.targets
  eng/helix/Helix.proj
  eng/helix/payload/dotnettest.cmd
  eng/helix/payload/dotnettest.sh
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Tests/Directory.Build.targets
  src/Tests/Helix.targets
Labels: testing

#4916 Enable Helix testing in builds
  dotnet-monitor.yml
  eng/helix/Helix.proj
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/test-binaries.yml
Labels: needs-review

#4934 Add pipeline for component governance scan on shipped code
  eng/pipelines/dotnet-monitor-cg.yml
Labels: servicing-patch, servicing-minor

#4948 CG pipeline: disable CI/PR triggers and enable CG
  eng/pipelines/dotnet-monitor-cg.yml
  eng/pipelines/jobs/build.yml
Labels: servicing-patch, servicing-minor

#4991 Collect exceptions from all processes and collect from startup
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IExceptionsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/Utilities.cs
  src/Tools/dotnet-monitor/DiagnosticLifetimeBackgroundService.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperationFactory.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/StartupHook/StartupHookEndpointInfoSourceCallback.cs
  src/Tools/dotnet-monitor/StartupHook/StartupHookService.cs
Labels: servicing-major
