Repository dotnet/dotnet-monitor, pull requests merged in 2023-01, with the labels that each got.

#3204 Create platform and TFM specific archives
  eng/Build.props
  eng/Signing.props
  eng/Versions.props
  eng/build.ps1
  eng/build.sh
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/platform-matrix.yml
  src/Directory.Build.props
  src/Tools/Directory.Build.props
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-major

#3210 [release/6.x] Create platform and TFM specific archives
  eng/Build.props
  eng/Signing.props
  eng/Versions.props
  eng/build.ps1
  eng/build.sh
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/platform-matrix.yml
  src/Directory.Build.props
  src/Tools/Directory.Build.props
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/dotnet-monitor-archive.proj
Labels: backport

#3220 [release/6.x] Do not pack shims for OSX
  src/Directory.Build.props
  src/Tools/Directory.Build.props
Labels: backport

#3222 Fix Component Governance
  eng/pipelines/jobs/build.yml
Labels: servicing-patch, servicing-major

#3231 [release/6.x] Use RID folders instead of osGroup/architecture folders
  CMakeSettings.json
  eng/Build-Native.cmd
  eng/build.sh
  eng/pipelines/jobs/platform-matrix.yml
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/NativeLibraryHelper.cs
  src/Tools/Directory.Build.props
Labels: backport

#3225 Update to latest .NET 8 SDK
  eng/Versions.props
  global.json
Labels: dependencies

#3242 Allow archiving without building product
  eng/AfterSolutionBuild.targets
  eng/Build-Native.cmd
  eng/Build.props
  eng/DotnetMonitorProjectToPublish.props
  eng/PublishProjects.targets
  eng/build.ps1
  eng/build.sh
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/Directory.Build.targets
  src/archives/PublishedProjectArchive.targets
  src/archives/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-major

#3280 [release/6.x] Allow archiving without building product
  eng/AfterSolutionBuild.targets
  eng/Build-Native.cmd
  eng/Build.props
  eng/DotnetMonitorProjectToPublish.props
  eng/PublishProjects.targets
  eng/build.ps1
  eng/build.sh
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/Directory.Build.targets
  src/archives/PublishedProjectArchive.targets
  src/archives/dotnet-monitor-archive.proj
Labels: backport

#3291 Enable checksum and publishing of archives
  eng/Publishing.props
  src/Directory.Build.targets
  src/archives/Directory.Build.props
  src/archives/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-major

#3294 Archive in separate job with license and TPN
  dotnet-monitor.yml
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/build-codeql.yml
  eng/pipelines/jobs/build-test.yml
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  eng/pipelines/jobs/platform-matrix.yml
  eng/pipelines/jobs/tpn.yml
  src/archives/Directory.Build.targets
  src/archives/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-major

#3307 Add missing entry for Microsoft.DotNet.BuildTasks.Archives dependency
  eng/Version.Details.xml
Labels: dependencies

#3308 Add missing entry for Microsoft.DotNet.BuildTasks.Archives dependency
  eng/Version.Details.xml
Labels: dependencies

#3301 Exception identification
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionIdentifier.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/ExceptionIdentifierTests.cs
Labels: servicing-major

#3334 Fix artifact publish metadata for NuGet packages
  eng/Publishing.props
Labels: servicing-patch, servicing-minor, servicing-major

#3339 Allow non-shipping assets in manifest generation
  src/Directory.Build.targets
Labels: servicing-patch, servicing-minor, servicing-major

#3376 Update Alpine build image to 3.14
  eng/pipelines/jobs/build.yml
Labels: servicing-patch, servicing-minor, servicing-major

#3382 Remove unused TraceEvent Windows-only dependencies two ways.
  src/Directory.Build.targets
Labels: servicing-patch, servicing-minor, servicing-major

#3380 Use templates for dependabot and configure public-feed dependencies
  .devcontainer/shared/scripts/container-creation.sh
  .devcontainer/shared/ytt-linux-amd64.sha
  .github/dependabot.template.yml
  .github/dependabot.yml
  .vscode/tasks.json
  eng/Versions.props
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  eng/dependabot/nuget.org/Directory.Build.props
  eng/dependabot/nuget.org/Packages.props
  eng/dependabot/nuget.org/Versions.props
  eng/dependabot/nuget.org/dependabot.csproj
Labels: DevEx

#3381 Allow bundling of cross-platform native libraries
  dotnet-monitor.yml
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/build-test.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  src/Directory.Build.props
  src/Tools/Directory.Build.props
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/Directory.Build.targets
  src/archives/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-minor, servicing-major

#3415 [release/6.x] Fix Microsoft.DotNet.Build.Tasks.Archives version entry
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies

#3413 [main] Fix Microsoft.DotNet.Build.Tasks.Archives version entry
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies

#3414 [release/7.x] Fix Microsoft.DotNet.Build.Tasks.Archives version entry
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies

#3418 [release/6.x] Run OpenApi tests for all TFMs
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj
Labels: backport

#3447 [release/6.x] Create archive symbols nupkg for symbol server publishing
  eng/Build.props
  eng/pipelines/jobs/build-archive.yml
  global.json
  src/Directory.Build.props
  src/Directory.Build.targets
  src/archives/Directory.Build.props
  src/archives/Directory.Build.targets
  src/archives/PublishedProjectArchive.targets
  src/archives/dotnet-monitor.props
  src/archives/pkgs/Directory.Build.props
  src/archives/pkgs/Directory.Build.targets
  src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
  src/archives/symbols/Directory.Build.props
  src/archives/symbols/Directory.Build.targets
  src/archives/symbols/dotnet-monitor/dotnet-monitor-symbols.proj
Labels: backport

#3451 [release/7.x] Swagger generation updates and minimize shipped dependencies
  documentation/openapi.json
  eng/Signing.props
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: backport

#3452 Include apphost in archives
  eng/PublishProjects.targets
Labels: servicing-patch, servicing-minor, servicing-major

#3462 Unified latest target framework spec and publish directory
  eng/Build.props
  eng/Common.props
  eng/DotnetMonitorProjectToPublish.props
  eng/Versions.props
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/build-test.yml
  src/archives/PublishedProjectArchive.targets
  src/archives/dotnet-monitor.props
  src/archives/pkgs/Directory.Build.targets
Labels: servicing-patch, servicing-minor, servicing-major

#3489 Mark dotnet-monitor as executable in archives
  src/archives/pkgs/Directory.Build.props
  src/archives/pkgs/Directory.Build.targets
  src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-minor, servicing-major

#3506 Sign published artifacts before archiving
  dotnet-monitor.yml
  eng/Signing.props
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/sign-binaries.yml
Labels: servicing-patch, servicing-minor, servicing-major

#3507 Mark archives for shipping
  src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
Labels: servicing-patch, servicing-minor, servicing-major
