Repository dotnet/dotnet-monitor, pull requests merged in 2023-02, with the labels that each got.

#3538 Use shipped version of dotnet-diagnostics
  eng/Versions.props
  eng/dependabot/nuget.org/Versions.props
Labels: dependencies

#3548 [release/8.0] Update dependencies and SDK to 8.0 Preview 1
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: dependencies

#3552 [main] Update dependencies and SDK to 8.0 Preview 2
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: dependencies

#3629 Refactor common archive logic into targets
  eng/AfterSolutionBuild.targets
  eng/Build.props
  src/archives/Directory.Build.props
  src/archives/PublishedProjectPackage.targets
  src/archives/dotnet-monitor/Package.props
  src/archives/dotnet-monitor/ProjectsToBuild.props
  src/archives/dotnet-monitor/ProjectsToPublish.props
  src/archives/dotnet-monitor/dotnet-monitor-archive.proj
  src/archives/dotnet-monitor/dotnet-monitor-symbols.proj
  src/archives/pkgs/Common.props
  src/archives/pkgs/Common.targets
  src/archives/pkgs/PublishedProject.targets
  src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
  src/archives/symbols/Common.props
  src/archives/symbols/Common.targets
  src/archives/symbols/PublishedProject.targets
  src/archives/symbols/dotnet-monitor/dotnet-monitor-symbols.proj
Labels: servicing-patch, servicing-minor, servicing-major

#3591 Allow per provider interval specification
  documentation/configuration/metrics-configuration.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Validation/CounterValidator.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsSettingsTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.Validate.cs
  src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetRequestDurationTriggerFactory.cs
  src/Tools/dotnet-monitor/CollectionRules/Triggers/EventCounterTriggerFactory.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: update-release-notes

#3750 [release/7.x] Port System.Diagnostics.Metrics
  documentation/openapi.json
  documentation/schema.json
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IMetricsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStoreService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/StreamingCounterLogger.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EventMetricsConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CounterPayload.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LiveMetricsTestConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/LiveMetricsTestUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/MetricsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/AzureBlob/AzureBlobEgressProviderTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MetricsScenario.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
Labels: backport

#3759 Add substitution tokens for other process info
  src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs
  src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs
  src/Tools/dotnet-monitor/ConfigurationTokenParser.cs
Labels: servicing-minor
