Repository dotnet/dotnet-monitor, pull requests merged in 2023-11, with the labels that each got.

#5629 8.0 compatibility docs
  cspell.json
  documentation/compatibility/8.0/README.md
Labels: documentation

#5637 Update docs to use final GitHub alert syntax
  documentation/api-key-format.md
  documentation/api-key-setup.md
  documentation/api/README.md
  documentation/api/collectionrules-get.md
  documentation/api/collectionrules-list.md
  documentation/api/collectionrules.md
  documentation/api/definitions.md
  documentation/api/dump.md
  documentation/api/exceptions-custom.md
  documentation/api/exceptions.md
  documentation/api/gcdump.md
  documentation/api/livemetrics-custom.md
  documentation/api/livemetrics-get.md
  documentation/api/logs-custom.md
  documentation/api/logs-get.md
  documentation/api/logs.md
  documentation/api/metrics.md
  documentation/api/operations-list.md
  documentation/api/parameters.md
  documentation/api/process-env.md
  documentation/api/process-get.md
  documentation/api/processes-list.md
  documentation/api/processes.md
  documentation/api/stacks.md
  documentation/api/trace-custom.md
  documentation/api/trace-get.md
  documentation/api/trace.md
  documentation/authentication.md
  documentation/collectionrules/collectionrules.md
  documentation/compatibility/7.0/README.md
  documentation/configuration/README.md
  documentation/configuration/collection-rule-configuration.md
  documentation/configuration/egress-configuration.md
  documentation/configuration/storage-configuration.md
  documentation/egress.md
  documentation/learningPath/README.md
  documentation/learningPath/aks.md
  documentation/release-process.md
Labels: documentation

#5651 Remove the apphost from the extensions
  src/archives/AzureBlobStorage/ProjectsToPublish.props
  src/archives/S3Storage/ProjectsToPublish.props
Labels: servicing-major

#5656 Add mutating profiler symbols to symbols package
  src/archives/dotnet-monitor-base/Package.props
Labels: servicing-major

#5667 Increase stopping event test timeouts
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectTraceTests.cs
Labels: testing

#5731 Release notes template update
  .github/actions/generate-release-notes/releaseNotes.template.md
Labels: needs-review
