Repository dotnet/dotnet-monitor, pull requests merged in 2023-03, with the labels that each got.

#3805 Basic exceptions store and route for default process
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionInstance.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsFormat.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionsStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IExceptionsOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/OutputStreamResult.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperationFactory.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: experimental-feature, update-release-notes

#3858 Publish guardian directory after validation
  dotnet-monitor.yml
Labels: servicing-patch, servicing-minor, servicing-major

#3859 Change call to UseApiKey to match pattern used elsewhere in test code
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
Labels: servicing-minor, servicing-major

#3790 [Learning Path] Using AKS To Test Dotnet Monitor Development
  documentation/learningPath/aks.md
Labels: documentation

#3883 Only publish platform neutral outputs on win-x64 release leg
  eng/pipelines/jobs/build-test.yml
  src/Microsoft.Diagnostics.Monitoring.StartupHook/ProjectsToPublish.props
Labels: servicing-patch, servicing-minor

#3884 Allow skipping publishing of projects in archive and package legs
  eng/AfterSolutionBuild.targets
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/archives/PublishedProjectPackage.targets
Labels: servicing-patch, servicing-minor

#3812 Adding `EventMeter` Trigger
  documentation/collectionrules/collectionruleexamples.md
  documentation/collectionrules/collectionrules.md
  documentation/configuration/collection-rule-configuration.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Options/CollectionRuleOptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MetricsScenario.cs
  src/Tools/dotnet-monitor/CollectionRules/KnownCollectionRuleTriggers.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventMeterOptions.Validate.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventMeterOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventMeterOptionsDefaults.cs
  src/Tools/dotnet-monitor/CollectionRules/Triggers/EventMeterTriggerFactory.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: update-release-notes

#3960 Refactor registration to artifact operation
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs
  src/Tools/dotnet-monitor/Logs/LogsOperation.cs
  src/Tools/dotnet-monitor/Logs/LogsOperationFactory.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs
  src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
  src/Tools/dotnet-monitor/PipelineArtifactOperation.cs
  src/Tools/dotnet-monitor/Trace/AbstractTraceOperation.cs
  src/Tools/dotnet-monitor/Trace/TraceOperation.cs
  src/Tools/dotnet-monitor/Trace/TraceOperationFactory.cs
  src/Tools/dotnet-monitor/Trace/TraceUntilEventOperation.cs
Labels: servicing-major, update-release-notes

#3952 Update SDK to final 8.0 Preview 2
  global.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
Labels: dependencies

#4098 Represent SDM Counters as Gauges In Prometheus Exposition Format
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
Labels: update-release-notes
