Repository dotnet/dotnet-monitor, pull requests merged in 2023-06, with the labels that each got.

#4553 [release/8.x] Stable version file and link
  .github/workflows/generate-release-notes.yml
  eng/Publishing.props
Labels: backport

#4598 Update diagnostics repo dependencies
  eng/Versions.props
Labels: dependencies

#4599 [release/7.x] Update diagnostics repo dependencies
  eng/Versions.props
Labels: dependencies

#4600 [release/6.x] Update diagnostics repo dependencies
  eng/Versions.props
Labels: dependencies

#4310 Enable UpDownCounter For Dotnet-Monitor
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
Labels: update-release-notes

#4616 Create single file bundle for evaluation purposes
  eng/AfterSolutionBuild.targets
  eng/PublishProjects.targets
  src/Tools/dotnet-monitor/LibrarySharing/DefaultSharedLibraryInitializer.cs
  src/Tools/dotnet-monitor/TestAssemblies.cs
  src/archives/dotnet-monitor/Package.props
  src/archives/dotnet-monitor/ProjectsToBuild.props
  src/archives/dotnet-monitor/ProjectsToPublish.props
  src/singlefile/dotnet-monitor/Common.props
  src/singlefile/dotnet-monitor/ProjectsToPublish.props
Labels: servicing-minor, servicing-major

#4756 [release/7.x] Cleanup release preparation stage
  eng/pipelines/stages/preparerelease.yml
Labels: backport

#4760 Fix update-docker tag workflow
  dotnet-monitor.yml
  eng/pipelines/stages/preparerelease.yml
Labels: servicing-patch, servicing-minor

#4777 Profiler runtime identifier fallback algorithm
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tools/dotnet-monitor/LoggingEventIds.cs
  src/Tools/dotnet-monitor/LoggingExtensions.cs
  src/Tools/dotnet-monitor/Profiler/ProfilerService.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: update-release-notes

#4764 Promote call stacks and exceptions to be supported features
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/CallStacksOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/CallStacksOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/CallStacksOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/IInProcessFeatureOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/InProcessFeaturesOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/InProcessFeaturesOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IExperimentalFlags.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessFeatures.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/InProcessFeaturesOptionsBinderTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestExperimentalFlags.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.Validate.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs
  src/Tools/dotnet-monitor/ConfigurationKeys.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsPostConfigureOptions.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs
  src/Tools/dotnet-monitor/Experimental/ExperimentalFlags.cs
  src/Tools/dotnet-monitor/Experimental/ExperimentalStartupLogger.cs
  src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeatureOptionsBinder.cs
  src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeatures.cs
  src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeaturesPostConfigureOptions.cs
  src/Tools/dotnet-monitor/InProcessFeatures/InProcessPostConfigureOptions.cs
  src/Tools/dotnet-monitor/RootOptions.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
  src/Tools/dotnet-monitor/Stacks/CallStacksPostConfigureOptions.cs
Labels: update-release-notes

#4785 Move MicrosoftDiagnosticsMonitoringShippedVersion to nuget.org dependabot props
  eng/Versions.props
  eng/dependabot/NuGet.config
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  eng/dependabot/net6.0/NuGet.config
  eng/dependabot/net7.0/NuGet.config
  eng/dependabot/netcoreapp3.1/NuGet.config
  eng/dependabot/nuget.org/Directory.Build.props
  eng/dependabot/nuget.org/Packages.props
  eng/dependabot/nuget.org/Versions.props
  eng/dependabot/nuget.org/dependabot.csproj
Labels: servicing-patch, servicing-minor
