Repository dotnet/dotnet-monitor, pull requests merged in 2023-09, with the labels that each got.

#5252 Add dotnet8-transport feed
  NuGet.config
Labels: servicing-major

#5326 Merge internal commits for release/8.x
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies

#5379 Reconcile className and typeName usage to typeName
  documentation/api/definitions.md
  documentation/api/exceptions-custom.md
  documentation/api/exceptions.md
  documentation/api/stacks.md
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsConfigurationSettings.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs
  src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.cpp
  src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.h
  src/Profilers/MonitorProfiler/MainProfiler/ExceptionTracker.cpp
  src/Profilers/MonitorProfiler/MainProfiler/ExceptionTracker.h
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/AssemblyProbePrep.cpp
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
Labels: breaking-change, update-release-notes

#5380 Update SDK to 8.0 RC 1
  global.json
Labels: dependencies

#5217 [Exceptions] Configuration-Level Filtering
  documentation/configuration/in-process-features-configuration.md
  documentation/openapi.json
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/IMethodDescription.cs
  src/Microsoft.Diagnostics.Monitoring.Options/InProcessFeaturesOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Microsoft.Diagnostics.Monitoring.StartupHook.csproj
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsSettingsFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/MethodDescription.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsStoreTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedConfigurations/InProcessFeatures.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/InProcessFeatures.json
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/SampleConfigurations/InProcessFeatures.json
  src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
Labels: update-release-notes

#5388 Fix build break due to new tests with old field references
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
Labels: needs-review

#5391 [Exceptions] `CollectExceptions` Action Filtering
  documentation/configuration/collection-rule-configuration.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Options/CollectionRuleOptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectExceptionsAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectExceptionsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectExceptionsOptionsExtensions.cs
Labels: update-release-notes, needs-review

#5397 Update GET livemetrics route to use metrics configuration
  documentation/api/definitions.md
  documentation/api/livemetrics-get.md
  documentation/configuration/collection-rule-configuration.md
  documentation/configuration/metrics-configuration.md
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsSettingsTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptionsExtensions.cs
Labels: breaking-change, update-release-notes

#5412 Remove custom XUnit version property
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
Labels: servicing-patch

#5426 Remove explicit IdentityModel dependencies
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-patch

#5428 [main] Remove explicit IdentityModel dependencies
  eng/dependabot/Packages.props
  eng/dependabot/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: backport

#5443 Switch to shipped Microsoft.Diagnostics.Monitoring libraries
  eng/Versions.props
Labels: dependencies
