Repository dotnet/dotnet-monitor, pull requests merged in 2024-08, with the labels that each got.

#7141 Add Azure Linux 3.0 helix queues
  eng/helix/Helix.proj
Labels: servicing-minor

#7153 [feature/9.x] Update .NET SDK
  global.json
Labels: dependencies

#7052 Update view-merged-configuration : update command
  documentation/configuration/view-merged-configuration.md
Labels: documentation, needs-review

#7211 [release/6.x] Get build data using darc instead of maestro web api
  eng/pipelines/stages/preparerelease.yml
  eng/release/Scripts/GetBuildVersion.ps1
  eng/release/Scripts/GetDarcBuild.ps1
Labels: backport
