Repository dotnet/dotnet-monitor, pull requests merged in 2024-04, with the labels that each got.

#6398 Enable spectre-mitigations for native builds
  CMakeLists.txt
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: servicing-patch, servicing-minor, servicing-major

#6401 [release/7.x] Enable spectre-mitigations for native builds
  CMakeLists.txt
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: backport

#6402 [release/6.x] Enable spectre-mitigations for native builds
  CMakeLists.txt
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: backport

#6348 Support collecting GC collect only trace using a simplified profile
  documentation/openapi.json
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/TraceProfile.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs
Labels: update-release-notes

#5911 [feature/9.x]Remove test disablements
  src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs
Labels: needs-review

#6488 [release/6.x] Enable AAD signing key issuer validation for API Key auth
  eng/dependabot/independent/Packages.props
  eng/dependabot/independent/Versions.props
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: backport

#6456 Add issuer and expiration validation for API keys
  documentation/api-key-format.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: servicing-patch, servicing-minor, servicing-major, breaking-change

#6272 Replace LogEmittingProbes with EventSourceEmittingProbes and add support for artifact egress on the 'POST /parameters' route.
  documentation/api/README.md
  documentation/api/definitions.md
  documentation/api/parameters.md
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Eventing/AsyncParameterCapturingEventSource.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Eventing/ParameterCapturingEventSource.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/EventSourceEmittingProbes.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/MethodSignature.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterSignature.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ResolvedParameterInfo.cs
  src/Microsoft.Diagnostics.Monitoring.Options/CapturedParameterFormat.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypeUtilities.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ICaptureParametersOperationFactory.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CapturedParametersResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/InProcessEgressOperation.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/CapturedParametersFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/CapturedParametersJsonFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/CapturedParametersTextFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/ICapturedParameters.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/ParameterInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodSignatureTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperationFactory.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CapturedParameters.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CapturedParametersBuilder.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CapturedParametersWriter.cs
  src/Tools/dotnet-monitor/ParameterCapturing/EventParameterCapturingPipeline.cs
  src/Tools/dotnet-monitor/ParameterCapturing/ParameterCapturingEvents.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: breaking-change, experimental-feature, update-release-notes

#6489 [release/8.0] Add issuer and expiration validation for API keys
  documentation/api-key-format.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: backport

#6490 [release/7.x] Add issuer and expiration validation for API keys
  documentation/api-key-format.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: backport

#6491 [release/6.x] Add issuer and expiration validation for API keys
  documentation/api-key-format.md
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tools/dotnet-monitor/Auth/AuthConfiguration.cs
  src/Tools/dotnet-monitor/Auth/GeneratedJwtKey.cs
  src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs
  src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfiguration.cs
  src/Tools/dotnet-monitor/Auth/MonitorApiKeyPostConfigure.cs
  src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
Labels: backport

#6549 [release/8.0] Replace SwaggerUI and SwaggerScope option with OpenAPI document
  Directory.Packages.props
  documentation/schema.json
  eng/Signing.props
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/IAuthenticationConfigurator.cs
  src/Tools/dotnet-monitor/Auth/NoAuth/NoAuthConfigurator.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/Swagger/SwaggerProviderExtensions.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: backport

#6550 [release/7.x] Replace SwaggerUI and SwaggerScope option with OpenAPI document
  documentation/schema.json
  eng/Signing.props
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/IAuthenticationConfigurator.cs
  src/Tools/dotnet-monitor/Auth/NoAuth/NoAuthConfigurator.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/Swagger/SwaggerProviderExtensions.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: backport
