Repository dotnet/dotnet-monitor, pull requests merged in 2024-07, with the labels that each got.

#6932 [Nullable Context] Enable on `Microsoft.Diagnostics.Monitoring.ConfigurationSchema`
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/ExperimentalSchemaProcessor.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/ConsoleFormatterOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/ConsoleLoggerOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/JsonConsoleFormatterOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/LogLevelOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/LoggingOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/RootOptions.Logging.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/SimpleConsoleFormatterOptions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectDumpOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectExceptionsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectGCDumpOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/ExecuteOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/GetEnvironmentVariableOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/LoadProfilerOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/SetEnvironmentVariableOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Actions/TraceEventFilter.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleActionDefaultsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleActionOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleDefaultsOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleTriggerOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/RegularExpressionsAttribute.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/TemplateOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestCountOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestDurationOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetResponseStatusOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventMeterOptions.cs
  src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/IAspNetActionPathFilters.cs
  src/Tools/dotnet-monitor/RootOptions.cs
Labels: needs-review

#7053 Update Azure Core Version
  Directory.Packages.props
  eng/dependabot/independent/Versions.props
Labels: servicing-minor

#7070 [release/8.0] Manual Backport Azure Core Pinned Version
  Directory.Packages.props
  eng/dependabot/independent/Versions.props
Labels: backport
