Repository dotnet/dotnet-monitor, pull requests merged in 2024-01, with the labels that each got.

#5795 [Parameter Capturing] Refactor probe management API to accept more detailed boxing instructions
  cspell.json
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/BoxingInstructions.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/BoxingTokensSignatureProvider.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/FunctionProbesManager.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/ProfilerAbi.cs
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInjector.cpp
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInjector.h
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.cpp
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.h
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/BoxingInstructionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/FunctionProbes/ProfilerAbiTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodResolverTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs
Labels: experimental-feature

#5800 [Parameter Capturing] Refactor reflection-only boxing logic into new method
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingInstructions.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingTokensSignatureProvider.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/FunctionProbesManager.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/BoxingInstructionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodResolverTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs
Labels: experimental-feature

#5838 Replace tagBuildOrRelease with Powershell inline script
  eng/pipelines/stages/preparerelease.yml
Labels: servicing-patch, servicing-minor, servicing-major

#5850 Rename packages to framework 9
  eng/Version.Details.xml
Labels: dependencies

#5812 [Parameter Capturing] Add support for generics, tuples, and nullable value types
  documentation/api/parameters.md
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingInstructions.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingTokensSignatureProvider.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/MethodDefinitionExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/ProfilerAbi.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingStrings.resx
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInjector.h
  src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.cpp
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/BoxingInstructionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/MethodDefinitionExtensionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/SampleMethods.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/FunctionProbes/FunctionProbesScenario.cs
Labels: experimental-feature, update-release-notes

#5883 Update sdk
  global.json
Labels: dependencies

#5881 [releases.json] Clear original date when promoting a preview release to rtm
  .github/actions/update-releases-json/index.js
Labels: github_actions

#5912 Update xcopy
  global.json
Labels: dependencies
