Repository dotnet/dotnet-monitor, pull requests merged in 2024-10, with the labels that each got.

#7379 Document breaking Entra ID configuration change
  cspell.json
  documentation/compatibility/9.0/README.md
  documentation/compatibility/README.md
  documentation/configuration/azure-ad-authentication-configuration.md
Labels: documentation

#7382 Add security considerations for Entra ID auth
  documentation/configuration/azure-ad-authentication-configuration.md
  documentation/security-considerations.md
Labels: documentation

#7395 [release/8.0] Ensure exception event source listener is running before applying startup hook
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/DiagnosticLifetimeBackgroundService.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs
Labels: backport

#7388 Add security considerations for managing secrets
  documentation/configuration/configuration-sources.md
  documentation/configuration/egress-configuration.md
  documentation/security-considerations.md
Labels: documentation

#7400 Update Learning Path Staleness Check (Pt. 2)
  .github/actions/learning-path-staleness-check/index.js
Labels: needs-review

#7399 [release/6.x] Disable Azurite tests
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs
Labels: needs-review

#7405 Security considerations for metrics
  documentation/configuration/metrics-configuration.md
  documentation/security-considerations.md
Labels: documentation

#7470 Fix runtime framework package version name
  .github/dependabot.template.yml
  .github/dependabot.yml
Labels: needs-review

#7480 [main] Update SDK
  global.json
Labels: dependencies

#7481 [feature/9.x] Update SDK
  global.json
Labels: dependencies

#7482 [release/8.0] Update SDK
  global.json
Labels: dependencies

#7478 [release/8.0] Replace COMPlus with DOTNET prefix
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DumpTestUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs
  src/Tools/dotnet-monitor/RuntimeInfo.cs
Labels: backport

#7504 Update documentation around `/stacks` and `parameterTypes`
  documentation/api/definitions.md
  documentation/api/stacks.md
Labels: documentation

#7532 Hide frames with `StackTraceHiddenAttribute` from `/exceptions` and `/stacks`
  documentation/api/definitions.md
  documentation/api/exceptions.md
  documentation/api/stacks.md
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs
  src/Profilers/CommonMonitorProfiler/CommonUtilities/TypeNameUtilities.cpp
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/HiddenFrameTestMethods.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksWorker.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
Labels: update-release-notes

#7550 [feature/9.x] Use official diagnostic releases
  eng/Versions.props
Labels: dependencies

#7571 [Experimental] Add new server endpoint pruning algorithm
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfo/ServerEndpointTrackerV2Tests.cs
  src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointTrackerv2.cs
  src/Tools/dotnet-monitor/Experimental/ExperimentalFeatureIdentifiers.cs
  src/Tools/dotnet-monitor/Experimental/ExperimentalStartupLogger.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: experimental-feature
