Repository dotnet/dotnet-monitor, pull requests merged in 2024-09, with the labels that each got.

#7293 [release/6.x] Update public Linux build machines to Ubuntu 22.04
  eng/pipelines/jobs/build.yml
Labels: backport

#7301 Prevent collected exceptions from being dropped due to null event values
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs
Labels: update-release-notes

#7342 Ensure exception event source listener is running before applying startup hook
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/DiagnosticLifetimeBackgroundService.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs
Labels: update-release-notes

#7365 [feature/9.x] Require setting `TenantId` when configuring `AzureAd` authentication
  documentation/schema.json
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptionsDefaults.cs
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptionsExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/AzureAdOptionsTests.cs
  src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs
Labels: breaking-change, update-release-notes

#7369 Add WIP document for security considerations
  SECURITY.md
  documentation/README.md
  documentation/security-considerations.md
Labels: documentation
