Repository dotnet/dotnet-monitor, pull requests merged in 2024-03, with the labels that each got.

#6155 Skip `CollectionRulePipeline_EventMeterTriggerTest_Histogram_GreaterThan`
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
Labels: testing

#6146 Replace SwaggerUI and SwaggerScope option with OpenAPI document
  Directory.Packages.props
  documentation/README.md
  documentation/authentication.md
  documentation/configuration/azure-ad-authentication-configuration.md
  documentation/learningPath/api.md
  documentation/openapi.md
  documentation/schema.json
  documentation/swagger-ui.md
  eng/Signing.props
  src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs
  src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
  src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs
  src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs
  src/Tools/dotnet-monitor/Auth/IAuthenticationConfigurator.cs
  src/Tools/dotnet-monitor/Auth/NoAuth/NoAuthConfigurator.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/Strings.Designer.cs
  src/Tools/dotnet-monitor/Strings.resx
  src/Tools/dotnet-monitor/Swagger/SwaggerProviderExtensions.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: servicing-patch, servicing-minor, servicing-major, breaking-change, update-release-notes

#6172 Branch sync improvements
  .gitattributes
  .github/workflows/sync-branches.yml
Labels: github_actions

#6212 [release/6.x] Remove unused pipeline from repository root
  dotnet-monitor.yml
Labels: backport

#6213 [release/7.x] Remove unused pipeline from repository root
  dotnet-monitor.yml
Labels: backport

#6241 [release/8.0] 1ES pipeline template conversion
  eng/pipelines/dotnet-monitor-cg.yml
  eng/pipelines/dotnet-monitor-codeql.yml
  eng/pipelines/dotnet-monitor-official.yml
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/dotnet-monitor-release.yml
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/build-binaries.yml
  eng/pipelines/jobs/build-codeql.yml
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  eng/pipelines/jobs/platform-matrix.yml
  eng/pipelines/jobs/sign-binaries.yml
  eng/pipelines/jobs/test-binaries.yml
  eng/pipelines/jobs/tpn.yml
  eng/pipelines/stages/preparerelease.yml
  eng/pipelines/steps/publish-build-artifacts.yml
  eng/pipelines/steps/publish-pipeline-artifact.yml
  eng/pipelines/templates/pipeline-template-1es.yml
  eng/pipelines/templates/pipeline-template-legacy.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: backport

#6257 Reenable log publishing
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  eng/pipelines/jobs/sign-binaries.yml
Labels: servicing-patch, servicing-minor

#6285 [release/6.x] Use long-term pool images
  eng/pipelines/jobs/build.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: backport

#6280 Update EOL versions
  eng/helix/Helix.proj
  eng/pipelines/templates/pipeline-template.yml
Labels: auto-merge

#6301 [release/7.x] Minimize printing of potential secrets in tests
  src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
Labels: backport

#6299 Minimize printing of potential secrets in tests
  src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
Labels: servicing-patch, servicing-minor, servicing-major

#6302 [release/6.x] Minimize printing of potential secrets in tests
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ProfilerHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
Labels: backport

#6314 [release/7.x] 1ES pipeline template conversion
  eng/pipelines/dotnet-monitor-cg.yml
  eng/pipelines/dotnet-monitor-codeql.yml
  eng/pipelines/dotnet-monitor-official.yml
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/dotnet-monitor-release.yml
  eng/pipelines/jobs/build-archive.yml
  eng/pipelines/jobs/build-codeql.yml
  eng/pipelines/jobs/build-test.yml
  eng/pipelines/jobs/build.yml
  eng/pipelines/jobs/pack-sign-publish.yml
  eng/pipelines/jobs/platform-matrix.yml
  eng/pipelines/jobs/sign-binaries.yml
  eng/pipelines/jobs/tpn.yml
  eng/pipelines/stages/preparerelease.yml
  eng/pipelines/steps/publish-build-artifacts.yml
  eng/pipelines/steps/publish-pipeline-artifact.yml
  eng/pipelines/templates/pipeline-template-1es.yml
  eng/pipelines/templates/pipeline-template-legacy.yml
  eng/pipelines/templates/pipeline-template.yml
Labels: backport

#6317 [release/7.x] Enable BinSkim, PoliCheck, and TSA
  eng/pipelines/dotnet-monitor-official.yml
Labels: backport
