Repository dotnet/dotnet-monitor, pull requests merged in 2024-06, with the labels that each got.

#6755 Add documentation note about in-process features are only supported in Listen mode.
  .github/linters/check-markdown-links-config.json
  .github/workflows/check-markdown-links.yml
  documentation/api/definitions.md
  documentation/api/stacks.md
  documentation/configuration/in-process-features-configuration.md
Labels: documentation, dependencies

#6781 Fake version for sdkplacholder
  eng/Version.Details.xml
  eng/Versions.props
Labels: dependencies, needs-review

#6782 Update parent dependency
  eng/Version.Details.xml
Labels: dependencies

#6821 Update global.json
  global.json
Labels: dependencies

#6837 Fix more InlineData nullable parameters
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/DebuggerDisplayFormatterTests.cs
Labels: needs-review

#6831 [Egress provider - S3] Support KMS encryption for artifacts
  documentation/configuration/egress-configuration.md
  documentation/schema.json
  src/Extensions/S3Storage/OptionsDisplayStrings.Designer.cs
  src/Extensions/S3Storage/OptionsDisplayStrings.resx
  src/Extensions/S3Storage/S3Storage.cs
  src/Extensions/S3Storage/S3StorageEgressProviderOptions.cs
Labels: update-release-notes

#6839 Add mvid and mdtoken to callstackframe
  documentation/api/definitions.md
  documentation/api/exceptions.md
  documentation/api/stacks.md
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSourceIdentifierCacheCallback.cs
  src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionGroupIdentifierCache.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackData.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameCache.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameFormatter.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameIdentificationEvents.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs
  src/Profilers/MonitorProfiler/Stacks/StacksEventProvider.cpp
  src/Profilers/MonitorProfiler/Stacks/StacksEventProvider.h
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionGroupIdentifierCacheTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj
  src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs
  src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipelineNameCache.cs
  src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
Labels: update-release-notes

#6906 [release/6.x] Update build asset staging to use managed identity
  eng/pipelines/stages/preparerelease.yml
  eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs
  eng/release/DiagnosticsReleaseTool/Config.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj
  eng/release/Directory.Build.props
  eng/release/Scripts/AcquireBuild.ps1
Labels: backport

#6903 [release/8.0] Update build asset staging to use managed identity
  eng/pipelines/stages/preparerelease.yml
  eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs
  eng/release/DiagnosticsReleaseTool/Config.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs
  eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj
  eng/release/Directory.Build.props
  eng/release/Scripts/AcquireBuild.ps1
Labels: backport, needs-review
