Repository dotnet/dotnet-monitor, pull requests merged in 2024-05, with the labels that each got.

#6564 Update to latest 8.0 SDK
  global.json
Labels: dependencies

#6570 Add semaphore around service scopes dictionary
  src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
Labels: servicing-minor, update-release-notes

#6626 [Egress providers - S3 store] Add support for service accounts when running dotnet monitor in kubernetes
  Directory.Packages.props
  documentation/configuration/egress-configuration.md
  eng/Signing.props
  eng/dependabot/independent/Packages.props
  eng/dependabot/independent/Versions.props
  src/Extensions/S3Storage/S3Storage.csproj
Labels: update-release-notes

#6685 Remove debug legs from CI build
  eng/pipelines/dotnet-monitor-official.yml
Labels: servicing-patch, servicing-minor, servicing-major

#6688 [release/6.x] Remove debug legs from CI build
  eng/pipelines/dotnet-monitor-official.yml
Labels: backport

#6695 [Parameter Capturing] Fix race condition when starting operation
  src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs
Labels: experimental-feature

#6686 Prevent operations from getting stuck in the `Starting` state
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/OperationExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationServiceTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
Labels: bug, update-release-notes

#6665 Fix ErrorMessage_CouldNotMapToAction usage
  src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs
Labels: servicing-patch, servicing-minor, servicing-major, update-release-notes

#6698 Sync feature/parameter-capturing/startup-hook
  .github/dependabot.template.yml
  .github/dependabot.yml
  .github/releases.json
  .github/workflows/cleanup-releases.yml
  .github/workflows/post-release.yml
  .github/workflows/spellcheck.yml
  .github/workflows/sync-branches.yml
  CMakeLists.txt
  Directory.Packages.props
  documentation/configuration/egress-configuration.md
  documentation/openapi.json
  documentation/releaseNotes/releaseNotes.v6.3.6.md
  documentation/releaseNotes/releaseNotes.v7.3.4.md
  documentation/releaseNotes/releaseNotes.v8.0.2.md
  documentation/releaseNotes/releaseNotes.v9.0.0-preview.4.md
  documentation/releases.md
  eng/Signing.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates-official/job/source-index-stage1.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/dependabot/independent/Packages.props
  eng/dependabot/independent/Versions.props
  eng/dependabot/net6.0/Versions.props
  eng/dependabot/net7.0/Versions.props
  eng/dependabot/net8.0/Versions.props
  eng/native/override/configurecompiler.cmake
  eng/pipelines/dotnet-monitor-official.yml
  global.json
  src/Extensions/S3Storage/S3Storage.csproj
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/OperationExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationServiceTests.cs
  src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
  src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs
  src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs
  src/Tools/dotnet-monitor/ParameterCapturing/EventParameterCapturingPipeline.cs
Labels: needs-review

#6703 [release/8.0] Prevent operations from getting stuck in the `Starting` state
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperationStore.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/OperationExtensions.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationServiceTests.cs
  src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
Labels: backport

#6728 Use sentinel package for installable SDK version
  eng/Version.Details.xml
  eng/Versions.props
  eng/helix/Helix.proj
Labels: needs-review
