Repository dotnet/dotnet-monitor, pull requests merged in 2025-03, with the labels that each got.

#7977 Add `Capabilities` to `/info` Route
  documentation/api/definitions.md
  documentation/api/info.md
  documentation/openapi.json
  src/Microsoft.Diagnostics.Monitoring.Options/CallStacksOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptions.cs
  src/Microsoft.Diagnostics.Monitoring.Options/IMonitorCapability.cs
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorCapability.cs
  src/Microsoft.Diagnostics.Monitoring.Options/MonitorCapabilityConstants.cs
  src/Microsoft.Diagnostics.Monitoring.Options/ParameterCapturingOptions.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.WebApi/Models/DotnetMonitorInfo.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs
  src/Tools/dotnet-monitor/CallStacksCapability.cs
  src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
  src/Tools/dotnet-monitor/ExceptionsCapability.cs
  src/Tools/dotnet-monitor/HttpEgressCapability.cs
  src/Tools/dotnet-monitor/MetricsCapability.cs
  src/Tools/dotnet-monitor/ParametersCapability.cs
  src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Labels: update-release-notes

#7926 Change deployment samples to be ready-to-deploy files
  documentation/docker-compose.md
  documentation/kubernetes.md
  samples/Docker/compose.yaml
  samples/Kubernetes/deployment.yaml
Labels: no-recent-activity

#8020 Code flow updates
  .github/workflows/sync-branches.yml
Labels: needs-review

#8021 [feature/10.0] Initial 10.0 versioning
  eng/Versions.props
Labels: dependencies

#8022 Limit managed entry point assembly tests to net8.0 and higher
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs
Labels: needs-review
