Repository dotnet/dotnet-monitor, pull requests merged in 2025-01, with the labels that each got.

#7799 Remove `xcopy-msbuild` version for `release/9.x`
  global.json
Labels: dependencies

#7869 Merge main to release/8.x
  .github/dependabot.template.yml
  .github/dependabot.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/sdk-task.ps1
  eng/common/tools.ps1
  eng/dependabot/independent/Versions.props
  global.json
  src/Extensions/AzureBlobStorage/Program.cs
  src/Extensions/S3Storage/Program.cs
  src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Scenarios/ExceptionThrowCatchScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Scenarios/ExceptionThrowCrashScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AspNetScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AsyncWaitScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/EnvironmentVariablesScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/FunctionProbes/FunctionProbesScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MetricsScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ParameterCapturingScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksScenario.cs
  src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/TraceEventsScenario.cs
  src/Tools/dotnet-monitor/Program.cs
Labels: needs-review

#7885 Only run x64 Helix tests in public
  eng/pipelines/dotnet-monitor-cg.yml
  eng/pipelines/dotnet-monitor-codeql.yml
  eng/pipelines/dotnet-monitor-official.yml
  eng/pipelines/dotnet-monitor-public.yml
  eng/pipelines/jobs/platform-matrix.yml
Labels: servicing-patch, servicing-minor, servicing-major

#7887 [release/8.x] Use shipping diagnostics monitoring library version
  eng/Versions.props
Labels: dependencies

#7893 Remove feature/9.x from scheduled builds
  eng/pipelines/dotnet-monitor-official.yml
Labels: servicing-patch, servicing-minor, servicing-major
